name: Docker Build and Push

on:
  push:
    branches:
      - main
      - semistable
      - '**'         # Optional: catch all branches if desired
    tags:
      - '*'          # Trigger on all tags

permissions:
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Determine Docker tags
        id: vars
        run: |
          DOCKER_USER=${{ secrets.DOCKER_USERNAME }}
          TAGS=""
          BRANCH="${GITHUB_REF#refs/heads/}"
          SHA_TAG="${DOCKER_USER}/dolla:${GITHUB_SHA}"

          if [[ "$GITHUB_REF" == refs/heads/main ]]; then
            TAGS="${DOCKER_USER}/dolla:latest,${DOCKER_USER}/dolla:main"
          elif [[ "$GITHUB_REF" == refs/heads/* ]]; then
            TAGS="${DOCKER_USER}/dolla:${BRANCH}"
          else
            TAGS="${SHA_TAG}"
          fi

          echo "tag_list=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tag_list }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
