name: Secure Docker Build and Push

on:
  push:
    branches:
      - main
      - semistable

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python  # change this to match your project

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker:
    name: Build and Push Docker Image
    needs: codeql
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/semistable'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t myimage:tmp .

      - name: Tag & Push Docker image
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Tagging as latest"
            docker tag myimage:tmp $IMAGE:latest
            docker push $IMAGE:latest
          elif [[ "${GITHUB_REF}" == "refs/heads/semistable" ]]; then
            echo "Tagging as semistable"
            docker tag myimage:tmp $IMAGE:semistable
            docker push $IMAGE:semistable
          fi
        env:
          IMAGE: mydockerhubuser/myimage  # ✅ FIXED: define environment variable here
