name: Docker Build and Push

on:
  push:
    branches:
      - main
      - semistable      # Add semistable branch here
    tags:
      - '*'             # Trigger on all tags

permissions:
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Determine additional tag
        id: vars
        run: |
          DOCKER_USER=${{ secrets.DOCKER_USERNAME }}
          TAG_LIST=""
          IS_TAG=false

          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            TAG_LIST="${DOCKER_USER}/dolla:latest,${DOCKER_USER}/dolla:${GITHUB_SHA}"
          elif [[ "${GITHUB_REF}" == refs/heads/semistable ]]; then
            # For semistable branch, push with semistable tag and SHA tag
            TAG_LIST="${DOCKER_USER}/dolla:semistable,${DOCKER_USER}/dolla:${GITHUB_SHA}"
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_LIST="${DOCKER_USER}/dolla:latest,${DOCKER_USER}/dolla:${GITHUB_SHA},${DOCKER_USER}/dolla:semistable"
            IS_TAG=true
          else
            # fallback, just use SHA tag
            TAG_LIST="${DOCKER_USER}/dolla:${GITHUB_SHA}"
          fi

          echo "tag_list=$TAG_LIST" >> $GITHUB_OUTPUT
          echo "is_tag=$IS_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.tag_list }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
